### ISSUE TITLE
Suggestion: display "excess" instead of "remaining" if the pipe's transfer rate is greater than the optimal flow

### ISSUE THREAD

**Issue by wellme** [Divran/greginator#1]
^Pretty much what the title says
(Example: gas turbine with large tritanium rotor running on hydrogen)![2019-04-29_21-02-22](https://user-images.githubusercontent.com/7041069/56935892-18930a00-6ac2-11e9-8611-b477cb712a48.png)

It would make it more obvious that the flow rate displayed is off in the other direction compared to the other categories, as opposed to just having the note in the second column.

I would do it myself but I'm JS intolerant (sorry).

**Comment by Divran** [comment]
Could do, but all of those numbers are always higher. None of them will ever suggest configurations which have a lower transfer rate than required.

EDIT: nevermind, I just checked and the "gregtech pumps" suggestion is actually lower than required. Guess I remembered wrong. Time to go dig around in the code I guess.

Alright I see what's wrong, I'll take a closer look when I get the time.

**Comment by Divran** [comment]
Done https://github.com/Divran/greginator/commit/039b173a9af9dfec17c5c022aa15e92410c17943

**Comment by wellme** [comment]
Actually that diff seems to break the non-huge turbines. For large, medium and small turbines, the website only displays GT/IC2 regulators.

**Comment by Divran** [comment]
whoops, fixing

**Comment by Divran** [comment]
fixed
